### ISSUE TITLE
Tag releases?

### ISSUE THREAD

**Issue by carlocab** [facebook/fb303#21]
Hi there,

I'm interested in packaging fb303 at Homebrew since it seems like it would enable useful features in our build of Watchman. However, we have a policy of building only from tagged commits.

Would you consider tagging releases in this repository? The same scheme used in other facebook repositories (e.g. folly, wangle, watchman) of weekly tags seems simple enough and works reasonably well for us.

Thanks!

**Comment by yfeldblum** [comment]
Thanks for asking.

The scheme used to tag weekly releases in folly, wangle, and watchman is now used to tag weekly pesudoreleases of fb303 as well.

[The tags page](https://github.com/facebook/fb303/tags) today shows the first weekly pseudorelease tag.

**Comment by carlocab** [comment]
Thanks very much!
