### ISSUE TITLE
Doesn't configure when fbthrift isn't built with python

### ISSUE THREAD

**Issue by yurivict** [facebook/fb303#4]
```
-- Configuring done
CMake Error at build/fbcode_builder/CMake/FBPythonBinary.cmake:494 (add_dependencies):
  The dependency target "FBThrift::thrift_py.py_lib" of target
  "fb303_thrift_py.py_sources_built" does not exist.
Call Stack (most recent call first):
  build/fbcode_builder/CMake/FBThriftPyLibrary.cmake:104 (add_fb_python_library)
  build/fbcode_builder/CMake/FBThriftLibrary.cmake:63 (add_fbthrift_py_library)
  fb303/thrift/CMakeLists.txt:15 (add_fbthrift_library)
```

Could you please add a cmake option to turn the python support on/off?

Thanks.

**Comment by chadaustin** [comment]
Hi @yurivict. Thanks for the report. This is low on our priority list, but it seems like a reasonable idea. If you have time to put together a patch, I'd support it.

In what environment are you trying to avoid the Python dependency?

**Comment by yurivict** [comment]
> In what environment are you trying to avoid the Python dependency?

bfthrift is installed as a FreeBSD package, and fb303 needs to build based on it.

**Comment by michel-slm** [comment]
I'm packaging fb303 for Fedora now, and noticed the same issue. It's a trivial fix so I'll put up a patch for review internally soon.
